### ISSUE TITLE
[BUG]`import janitor` causing `TypeError`

### ISSUE THREAD

**Issue by xujiboy** [pyjanitor-devs/pyjanitor#1201]
# Brief Description

Can not import janitor with version 0.24.0

# System Information

- Operating system: Linux 
- OS details (optional):  
- Python version (required): 3.8.13

# Minimally Reproducible Code

```
import janitor
```

# Error Messages

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jixux/miniconda3/envs/test/lib/python3.8/site-packages/janitor/__init__.py", line 9, in <module>
    from .functions import *  # noqa: F403, F401
  File "/home/jixux/miniconda3/envs/test/lib/python3.8/site-packages/janitor/functions/__init__.py", line 19, in <module>
    from .add_columns import add_columns
  File "/home/jixux/miniconda3/envs/test/lib/python3.8/site-packages/janitor/functions/add_columns.py", line 3, in <module>
    from janitor.utils import check, deprecated_alias
  File "/home/jixux/miniconda3/envs/test/lib/python3.8/site-packages/janitor/utils.py", line 216, in <module>
    *arguments: list[str],
TypeError: 'type' object is not subscriptable
```

**Comment by Zeroto521** [comment]
duplicate to #1200
