### ISSUE TITLE
Not able to import janitor.clean_name function - ImportError: cannot import name 'ABCPandasArray' from 'pandas.core.dtypes.generic'

### ISSUE THREAD

**Issue by roboes** [pyjanitor-devs/pyjanitor#1285]
# Brief Description

I am not able to import the function clean_name from pyjanitor. I get the following error: "ImportError: cannot import name 'ABCPandasArray' from 'pandas.core.dtypes.generic'". I am using the latest stable version of Python (3.11.5) and pyjanitor (v0.25.0).

# System Information

- Operating system: Windows
- OS details (optional):  Windows 10
- Python version (required): 3.11.5

# Minimally Reproducible Code

```
from janitor import clean_names
```

# Error Messages

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\roboes\AppData\Local\Programs\Python\Python311\Lib\site-packages\janitor\__init__.py", line 5, in <module>
    from .functions import *  # noqa: F403, F401
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roboes\AppData\Local\Programs\Python\Python311\Lib\site-packages\janitor\functions\__init__.py", line 25, in <module>
    from .coalesce import coalesce
  File "C:\Users\roboes\AppData\Local\Programs\Python\Python311\Lib\site-packages\janitor\functions\coalesce.py", line 7, in <module>
    from janitor.functions.utils import get_index_labels
  File "C:\Users\roboes\AppData\Local\Programs\Python\Python311\Lib\site-packages\janitor\functions\utils.py", line 19, in <module>
    from pandas.core.dtypes.generic import ABCPandasArray, ABCExtensionArray
ImportError: cannot import name 'ABCPandasArray' from 'pandas.core.dtypes.generic' (C:\Users\roboes\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\dtypes\generic.py)
```

**Comment by Flnch** [comment]
I had the same error while importing janitor in general via `import janitor`.

As a temporary fix, it works again if I explicitly downgrade the installed pandas package inside my Python venv from version 2.1.0 to 2.0.3: `(.venv) user@ubuntu:~/jupyter$ python3 -m pip install --force-reinstall -v "pandas==2.0.3"`. So it seems something changed with pandas 2.1.0 that breaks janitor.

**Comment by samukweku** [comment]
thanks @roboes and @Flnch for the feedback. i'll create a PR to fix the import error
