### ISSUE TITLE
importing janitor fails 

### ISSUE THREAD

**Issue by andersnev** [pyjanitor-devs/pyjanitor#1391]
# Brief Description

TypeError when importing janitor after updating to 0.28.0

# System Information

- Operating system: Linux
- Python version (required): 3.8.10

# Minimally Reproducible Code

````python
import janitor
````

# Error Messages

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workdir/.venv/lib/python3.8/site-packages/janitor/__init__.py", line 6, in <module>
    from .functions import *  # noqa: F403, F401
  File "/workdir/venv/lib/python3.8/site-packages/janitor/functions/__init__.py", line 43, in <module>
    from .expand_grid import cartesian_product, expand, expand_grid
  File "/workdir/.venv/lib/python3.8/site-packages/janitor/functions/expand_grid.py", line 143, in <module>
    by: str | list = None,
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by samukweku** [comment]
@andersnev thanks for the feedback. we just pushed a patch that should fix this. Kindly uninstall and reinstall pyjanitor and let's know if the error persists.

**Comment by andersnev** [comment]
Reinstalled pyjanitor and it works :)
