### ISSUE TITLE
Pandas and Compatibility

### ISSUE THREAD

**Issue by ramm001** [pyjanitor-devs/pyjanitor#835]
# Brief Description

Hello Everyone
    I downloaded pyjanitor a few weeks ago, and started using it on Windows 10 with python 3.6 and pandas 1.1.3 (all the installations were performed via anaconda). No problem whatsoever while running my code under these conditions. For many reasons it was more suitable to run my code in a Linux server (Centos) with python3.6 and pandas 0.25.1 installed, which ended up in a very "basic" error as it is detailed below (which boils down to `group() got an unexpected keyword argument 'dropna'` ). The error is produced in the very first call to the function `groupby_agg()` in my code. This, as i said above, gave no problems under Windows 10. Even though I know there might be some strong compatibility issues between these two OS's in many cases (...), my guess is that this is an issue of compatibility related to the versions of pandas, but I am not sure since I didn't find any way to track down if there are issues of pyjanitor with old pandas versions. On the other hand, I know I should provide you a fully-executable code, but if this is an already-known compatibility issue related to the pandas versions (which i was unable to find), it will suffice to know that the cause was that.

# System Information

- Operating system: Linux (Centos)  
- Python version (required): 3.6
- Pandas Version: 0.25.1
- Pyjanitor version: 0.20.14

# Minimally Reproducible Code

```
import pandas as pd
import janitor as jn

##-- HERE IS SOME CODE FILLING UP THE VI_DF DATAFRAME.
##-- ACTUALLY THE DATAFRAME VI_DF IS GOING TO BE RETURNED BY
##-- A FUNCTION NAMED downloading_ValRet --> THE CODE BELOW
##-- COMES AFTER 2 LINES OF CODE THAT FILL VI_DF.
##-- PLEASE: BELIEVE ME THAT THE VI_DF IS CORRECTLY FILLED
##-- WITH THE DATA, AS IT WAS DOUBLE CHECKED BY MYSELF.
##-- SEE THE ERROR MESSAGE PASTED BELOW.
##-- THE ERROR I GOT IS POINTING TO THE LAST LINE
##-- INSIDE THE groupby_agg, NAMELY, THE CALL TO agg_column_name 

VI_DF = VI_DF.sort_values(by = ['nemo', 'fecha']) \
.reset_index(drop = True) \
.assign(RENT_PER = lambda x : 1 + x['rent_clp_%']) \
.groupby_agg(
    by  = ['nemo'], 
   agg = 'cumprod', 
   new_column_name = 'rent_%_ACC',
   agg_column_name = 'RENT_PER'
)
```

# Error Messages

```
 Traceback (most recent call last):
  File "MAS_source.py", line 710, in <module>
    execution_in_loop()
  File "MAS_source.py", line 685, in execution_in_loop
    SM_DF    = main_dates(DATE_INI, DATE_END)
  File "MAS_source.py", line 645, in main_dates
    CH_DF = downloading_CHP(DATE_INI, DATE_END, 'S')
  File "MAS_source.py", line 129, in downloading_CHP
    VI_DF = downloading_ValRet(DATE_INI, DATE_END)  ##--> THIS FUNCTION CONTAINS THE PSEUDO-CODE FROM ABOVE
  File "MAS_source.py", line 91, in downloading_ValRet
    agg_column_name = 'RENT_PER'
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/pandas_flavor/register.py", line 29, in __call__
    return method(self._obj, *args, **kwargs)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/janitor/utils.py", line 273, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/janitor/functions.py", line 3775, in groupby_agg
    df[new_column_name] = df.groupby(by, dropna=dropna)[
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/pandas/core/generic.py", line 7894, in groupby
    **kwargs
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 2522, in groupby
    return klass(obj, by, **kwds)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 400, in __init__
    validate_kwargs("group", kwargs, {})
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/pandas/util/_validators.py", line 165, in validate_kwargs
    _check_for_invalid_keys(fname, kwargs, compat_args)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/pandas/util/_validators.py", line 134, in _check_for_invalid_keys
    "keyword argument '{arg}'".format(fname=fname, arg=bad_arg)
TypeError: group() got an unexpected keyword argument 'dropna'


```

**Comment by samukweku** [comment]
@ramm001 in pyjanitor v0.20.14 `group_agg` was updated to support null values during grouping. Could you kindly test with a lower version , possibly 0.20.13 to see if this persists?
